# **Day 09 - NumPy for Gene Expression Analysis**
Author: Jagriti Singh

Course: Python for Computational Biology

Repository: Python-for-Biologists

# **Introduction**


Modern biological research generates large numerical datasets.

Examples include:

• Gene expression levels

• RNA-Seq read counts

• Microarray intensities

• Protein abundances

• Clinical laboratory measurements

• Cell viability assays

• Drug response values

Processing such datasets using ordinary Python lists becomes inefficient.

NumPy provides a high-performance numerical computing library that enables efficient storage, manipulation, and statistical analysis of biological data.

This notebook introduces NumPy using practical examples from cancer genomics, transcriptomics, and computational biology.

# **Why NumPy Matters?**
#  Why is NumPy Important in Computational Biology?

Most computational biology analyses involve numerical data.

Examples include:

• Gene expression matrices

• RNA sequencing read counts

• Protein abundance measurements

• Clinical laboratory values

• DNA methylation scores

• Single-cell RNA sequencing

NumPy provides efficient numerical arrays and mathematical functions that form the foundation of scientific computing in Python.

Many widely used libraries such as Pandas, Scikit-learn, SciPy, TensorFlow, and Biopython are built upon NumPy arrays.

# **Learning Objectives**
After completing this notebook, I will be able to:

 * Import NumPy

* Create NumPy arrays

* Perform statistical calculations

* Conduct array arithmetic

* Generate random biological datasets

* Normalize gene expression values

* Apply NumPy to computational biology workflows

# **What is NumPy?**
NumPy (Numerical Python) is a scientific computing library that provides efficient multidimensional arrays and mathematical operations.

Compared with Python lists, NumPy arrays:

• Require less memory

• Perform calculations much faster

• Support vectorized mathematical operations

• Are ideal for handling biological datasets containing thousands of genes.

NumPy serves as the computational engine behind many bioinformatics and machine learning workflows.

In [2]:
#Import NumPy
import numpy as np

# **Explanation**
The standard alias **np** is universally used by researchers and data scientists when importing NumPy.

In [3]:
#Example 1 Creating a Gene Expression Array
gene_expression = np.array([

12.4,

8.6,

20.2,

17.8,

15.4,

10.9,

18.6,

9.7

])

print(gene_expression)

[12.4  8.6 20.2 17.8 15.4 10.9 18.6  9.7]


# **Explanation**
Each value represents the expression level of a specific gene.

Unlike Python lists, NumPy arrays are optimized for fast numerical computation and mathematical analysis.

# **Biological Interpretation**
Suppose these values represent normalized expression levels of eight cancer-related genes measured using RNA sequencing.

Researchers routinely analyze such numerical arrays before identifying differentially expressed genes or potential biomarkers.

In [4]:
#Example 2 Mean Gene Expression
print(np.mean(gene_expression))

14.2


# **Explanation**
The mean provides the average expression level across all genes.

Average expression is frequently reported during quality control and exploratory data analysis.

In [5]:
#Example 3 – Median Expression
print(np.median(gene_expression))

13.9


# **Biological Interpretation**
The median is less affected by extreme values and often provides a more robust measure of central tendency in biological datasets.

In [6]:
#Maximum Expression
print(np.max(gene_expression))

20.2


In [7]:
#Minimum Expression
print(np.min(gene_expression))

8.6


In [8]:
#Standard Deviation
print(np.std(gene_expression))

4.115519408288582


# **Explanation**
Standard deviation measures how much expression levels vary among genes.

Higher variation often indicates biological diversity or technical variability.

In [10]:
#Array Arithmetic
normalized = gene_expression / 10

print(normalized)

[1.24 0.86 2.02 1.78 1.54 1.09 1.86 0.97]


# **Biological Interpretation**
Normalization rescales expression values.

Normalization is a crucial preprocessing step before clustering, machine learning, and differential expression analysis.

In [11]:
#Random RNA-Seq Dataset
reads = np.random.randint(100,1000,20)

print(reads)

[457 773 902 911 139 818 667 694 141 232 921 985 787 248 330 312 499 375
 278 695]


# **Explanation**
This simulates sequencing read counts obtained from a hypothetical RNA sequencing experiment.

Although randomly generated, it resembles the structure of real count data.

In [12]:
#Biological Example
genes = np.array([

"TP53",

"BRCA1",

"EGFR",

"KRAS",

"MYC",

"ALK",

"BRAF",

"PIK3CA"

])

expression = np.array([

12.4,

8.6,

20.2,

17.8,

15.4,

10.9,

18.6,

9.7

])

for gene, exp in zip(genes, expression):

    print(gene, ":", exp)

TP53 : 12.4
BRCA1 : 8.6
EGFR : 20.2
KRAS : 17.8
MYC : 15.4
ALK : 10.9
BRAF : 18.6
PIK3CA : 9.7


# **Biological Interpretation**
This example links each gene to its corresponding expression level.

This structure closely resembles simplified gene expression matrices used in transcriptomics studies.

# **Research Note**
Large RNA-Seq experiments typically measure expression levels for over 20,000 genes.

Efficient numerical operations using NumPy become essential for analyzing datasets of this size.

# **Mini Exercise**
A researcher measured expression levels for six immune checkpoint genes.

Expression values:

7.5

12.8

18.9

22.1

15.3

9.6

Tasks:

1. Create a NumPy array.

2. Calculate:

• Mean

• Median

• Maximum

• Minimum

• Standard deviation

3. Normalize the values by dividing each value by 10.

In [14]:
#Solution
immune_expression = np.array([

7.5,

12.8,

18.9,

22.1,

15.3,

9.6

])

print("Mean:", np.mean(immune_expression))

print("Median:", np.median(immune_expression))

print("Maximum:", np.max(immune_expression))

print("Minimum:", np.min(immune_expression))

print("Standard Deviation:", np.std(immune_expression))

print("Normalized Values:")

print(immune_expression/10)

Mean: 14.366666666666667
Median: 14.05
Maximum: 22.1
Minimum: 7.5
Standard Deviation: 5.058875588727422
Normalized Values:
[0.75 1.28 1.89 2.21 1.53 0.96]


# **Research Challenge**
Imagine you downloaded RNA-Seq expression values for 500 genes from TCGA.

Design a NumPy workflow that:

• Calculates average expression

• Identifies highly expressed genes

• Normalizes expression values

• Computes standard deviation

• Prepares the data for downstream machine learning analysis

# **Career Connection**
NumPy is extensively used in:

* Computational Biology

* Bioinformatics

* Cancer Genomics

* Biomedical Data Science

* AI in Healthcare

* Machine Learning

* Drug Discovery

* Precision Medicine

# **Common Beginner Mistakes**
* Forgetting to import NumPy

* Mixing strings and numbers in the same array

* Using Python lists when numerical computation is required

* Confusing np.mean() with Python's built-in functions

* Ignoring data normalization before analysis

# **Key Takeaways**
* NumPy is the foundation of scientific computing in Python.

* NumPy arrays enable efficient analysis of large biological datasets.

* Statistical functions provide rapid insights into gene expression patterns.

* NumPy serves as the backbone for many advanced computational biology libraries.

# **Reflection**

My undergraduate project focused on the transcriptome-based analysis of competing endogenous RNA (ceRNA) networks associated with lung adenocarcinoma prognosis, where I analyzed gene expression profiles to understand cancer-associated regulatory mechanisms. At that time, much of my work relied on bioinformatics web platforms and manual interpretation of results. If the expression data had been organized as NumPy arrays, I could have efficiently calculate summary statistics, normalize expression values, compare multiple genes simultaneously, and perform large-scale numerical analyses using only a few lines of Python code. This has helped me appreciate the importance of scientific programming in computational biology and motivated me to integrate Python into future genomic and transcriptomic analyses.

# **Further Reading**
NumPy Documentation: https://numpy.org/doc/

SciPy Documentation: https://scipy.org/

Biopython Documentation: https://biopython.org/

TCGA Data Portal: https://portal.gdc.cancer.gov/

cBioPortal: https://www.cbioportal.org/

# **Day-9 Summary**
In this notebook, I learned how NumPy enables efficient numerical analysis of biological datasets. Using gene expression data as an example, I created arrays, performed statistical calculations, normalized expression values, and explored their applications in computational biology and cancer genomics.

These concepts form the mathematical foundation for biomedical data analysis, machine learning, and large-scale genomics research.